### ISSUE TITLE
Binary not working on Debian / WSL2

### ISSUE THREAD

**Issue by nurtext** [mogenius/podloxx#2]
Hi, 

wanted to try out podloxx on my local machine using Debian in WSL2 but for whatever reason, I simply can't run the provided file:

```
❯ uname -a
Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

❯ lsb_release --all
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

> curl -Lo podloxx https://github.com/mogenius/podloxx/releases/download/v1.0.11/podloxx-1.0.11-linux-amd64 && chmod 755 podloxx

❯ ./podloxx start
zsh: no such file or directory: ./podloxx

❯ file podloxx
podloxx: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, Go BuildID=eh0oa1gya3f4IOOPRKY7/VufWHdJ7f_WA5_RyDaax/PKmA5WMBlO-pItapc_oK/z2JtWgdhhrgMhSgAjYGO, stripped

❯ ls -la | grep podloxx
-rwxr-xr-x  1 cedric cedric 41625352 Dec  2 12:22 podloxx
```

Any ideas why it won't work?

**Comment by beneiltis** [comment]
Hey Cedric,

i am so sorry. We are rebuilding all binaries at the moment. There is a bug in the build-script. We will redeploy later today and than everything will work as expected :-)

Thx for your feedback.

I will close the ticket as soon as we finished our work.

**Comment by nurtext** [comment]
Hi Benedikt,

thanks for the quick feedback on this topic. Just take your time and have a nice weekend.

Cheers,
Cedric

**Comment by ruedigerp** [comment]
Hello @nurtext,

the release 1.0.2 was just published. 
Please test once with this version.

https://github.com/mogenius/podloxx/releases/tag/v1.0.2

Cya
  Rüdiger

**Comment by nurtext** [comment]
Still won't work:

```bash
❯ podloxx_link=$(curl -s https://api.github.com/repos/mogenius/podloxx/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep linux )
❯  curl -s -L -o podloxx ${podloxx_link}
❯ chmod 755 podloxx
❯ ./podloxx start
./podloxx: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
```

**Comment by nurtext** [comment]
Update: After installing libpcap-dev manually podloxx will start... but a standalone Go binary should work without loading any shared library at all, right?

**Comment by ruedigerp** [comment]
[podloxx-static.tar.gz](https://github.com/mogenius/podloxx/files/10277121/podloxx-static.tar.gz)

Hello, 

can you please test the binary in the attachment? 

Can you uninstall libpcap-dev before. 

The binary should be completely static now.
If you could test it and it works then we will create a new release with it. 

Many thanks for reporting & testing.
