### ISSUE TITLE
Meaning of release v1337

### ISSUE THREAD

**Issue by g1box** [mogenius/podloxx#3]
Hi,

just wanted to ask, if release v1337 has any purpose or was just a prove that using the build-client.sh with adapted parameters generates a new release in the repository. That would possably indicate that the circle of people able to do a release should be reduced to contributors or the building should be fully automated for security reasons as well as version conformance.

**Comment by beneiltis** [comment]
Jeah you are absolutely right. Please give us until monday. than everything will be ready and in place.

**Comment by ruedigerp** [comment]
Hello @nurtext,

the release 1.0.2 was just published. 

https://github.com/mogenius/podloxx/releases/tag/v1.0.2

have fun. 

Cya
  Rüdiger
