### ISSUE TITLE
Linux 1.02 version - main command doesn't work

### ISSUE THREAD

**Issue by krzwiatrzyk** [mogenius/podloxx#7]
I think some paths are hardcoded there:)

```
> podloxx
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
podloxx/utils.LoadDotEnv()
        /home/azureuser/Projects/Proj1/utils/utils.go:28 +0xcaa
main.main()
        /home/azureuser/Projects/Proj1/main.go:22 +0x78
```

**Comment by ruedigerp** [comment]
You call the binary without any parameters: 
`> podloxx`
Try: 
`> podloxx start`

**Comment by krzwiatrzyk** [comment]
Yea, I know, it starts this way. However, the main command shouldn't return such jibberish.

**Comment by ruedigerp** [comment]
I have a fix in develop that fixes this. 
But we still look at the issue #8 with k3s in peace. 
If we still have to change something for it and the changes are made quickly we will merge both together to main and then create a new release.
The error, in this issue, is only a small blemish. I hope that is ok for you. 
But thanks for reporting.
