### ISSUE TITLE
Podloxx UI stuck on LOADING INITIAL_DATA on K3s cluster

### ISSUE THREAD

**Issue by krzwiatrzyk** [mogenius/podloxx#8]
Cluster: k3s

![image](https://user-images.githubusercontent.com/52850037/208499381-f3095451-f9a5-4f0e-9067-0919924aca12.png)

**Comment by krzwiatrzyk** [comment]
K3s cluster is not mentioned in supported, I know, however it would be nice to have.

**Comment by ruedigerp** [comment]
k3s is https://www.k3s.io ?

I just installed this on a VM once and check it out. 

`
~# kubectl logs -f podloxx-56657b5ffd-6ss94
19:11:13.558 LoadDotEnv ▶ INFO 001 map[API_HOST:localhost API_PORT:1337 GIN_MODE:release PODLOXX_DIST:/app/dist REDIS_PORT:6379 REDIS_SERVICE_NAME:podloxx-redis-service STAGE:production]
19:11:13.585 LoadDotEnv ▶ NOTI 002 Key: STAGE => Element: production
19:11:13.585 LoadDotEnv ▶ NOTI 003 Key: API_HOST => Element: localhost
19:11:13.585 LoadDotEnv ▶ NOTI 004 Key: API_PORT => Element: 1337
19:11:13.585 LoadDotEnv ▶ NOTI 005 Key: GIN_MODE => Element: release
19:11:13.585 LoadDotEnv ▶ NOTI 006 Key: PODLOXX_DIST => Element: /app/dist
19:11:13.585 LoadDotEnv ▶ NOTI 007 Key: REDIS_PORT => Element: 6379
19:11:13.585 LoadDotEnv ▶ NOTI 008 Key: REDIS_SERVICE_NAME => Element: podloxx-redis-service
19:11:13.585 initRedis ▶ INFO 009 REDIS: Connecting to: podloxx-redis-service:6379
19:11:13.585 embedFs ▶ NOTI 00a Loaded 90 static files from embed.
19:11:13.589 initRedis ▶ CRIT 00b Could not connect to redis! (dial tcp: lookup podloxx-redis-service on 10.43.0.10:53: no such host)
`

I'll see why it doesn't work.

**Comment by krzwiatrzyk** [comment]
Yes, it's what I meant. K3s is a very popular K8s version (very lightweight).

**Comment by ruedigerp** [comment]
I have now run k3s on a remote VM and tested podloxx with it. 
In the browser console you can see that the connect from podloxx goes to localhost:1337. 
Since k3s is running remotely this can't work. 
We build a config parameter into podloxx. 

Until then you can help yourself with a SSH remote tunnel.
Download Podloxx on the k3s server and start it. 
The best is to start it in a screen.

On k3s host:
`
screen -L -Logfile podloxx.$(date +%Y.%m.%d.%H.%M.%S).log -dmS podloxx /bin/bash -c "/home/username/podloxx start"
`

On local host:
`
ssh -R 1337:127.0.0.1:1337 username@k3s.cluster.example.net
`

Then call in the browser: http://k3s.cluster.example.net:1337/podloxx 

Does that help you?

**Comment by krzwiatrzyk** [comment]
I'm a little bit lost.

According to: 
> A Podloxx namespace is created to isolate it from other workloads.
Set up RBAC for proper access control.
Start a memory-only redis. All DaemonSets will drop their data here.
Create a DaemonSet to scrape data from all nodes.
Launch a redis service to make the redis accessible via port forwarding.
Set up port forwarding for the redis service.
Start a web service locally to expose the Podloxx web application (which gathers the data from redis).
Launch the web application in a browser.

It should work for remote clusters (K3s running remotely doesn't differ much from AKS/EKS).

I see that under the hood:
- podloxx on `podloxx start` tries to create a port-forward for reddis (6439) - this is buggy, it doesn't work first time, I create this port-forward later manually.
```
22:11:25.931 StartPortForward ▶ INFO 013 Starting PortForward for podloxx-redis-54fdc8ff58-dcm2b ...

22:11:26.150 StartPortForward ▶ INFO 014 PortForward for podloxx-redis-54fdc8ff58-dcm2b is ready!

E1219 22:11:27.030603    3173 portforward.go:406] an error occurred forwarding 6379 -> 6379: error forwarding port 6379 to pod 9ba599444124b9558399266cde959d15d1810a5d83308b2367cc1d175005dc42, uid : failed to execute portforward in network namespace "/var/run/netns/cni-ed2a772f-4af3-bd5a-63e3-426682195686": failed to connect to localhost:6379 inside namespace "9ba599444124b9558399266cde959d15d1810a5d83308b2367cc1d175005dc42", IPv4: dial tcp4 127.0.0.1:6379: connect: connection refused IPv6 dial tcp6 [::1]:6379: connect: connection refused 

E1219 22:11:27.030864    3173 portforward.go:234] lost connection to pod

22:11:27.030 InitApi ▶ INFO 015 Waiting for redis to come alive: 127.0.0.1:6379
```



- additional podloxx pod is started in K8s - mentioned deamonset to scrape data I suppose
- a podloxx application is started that listens on port 1337? I suppose so because there is a GIN application started - logs are streamed to stdout, so I belive GIN app is feeded with data from Redis.

My issue is not from remote cluster issue I suppose. Check my podloxx logs:
![image](https://user-images.githubusercontent.com/52850037/208525950-400916d4-69c2-43ef-a457-13c7e0cab12b.png)

**Comment by beneiltis** [comment]
AMEN!
you are right in any way. 
We are having issues with the port-forwarding. I will look into it tomorrow morning. 

The cgroup problem you see in your log is because the cluster was setup without the PIDS flags:
https://stackoverflow.com/questions/65884578/kubernetes-kubeadm-init-cgroups-pids-missing

we are trying to find a solution for this. Any idea is welcome :-)

**Comment by krzwiatrzyk** [comment]
Great!:) 
I will look forward to any updates, I would love to test this tool (I worked with Mizu and loved it).  I will check that flag and this issue tomorrow - K3s is a common solution, probably other apps encountered similar issues.

**Comment by beneiltis** [comment]
Great. We just released a minor bugfix release. Including windows support. Tomorrow we will address the problems you reported. will keep you updated asap.

**Comment by ruedigerp** [comment]
@krzwiatrzyk Which kernel version is installed?
uname -a

**Comment by krzwiatrzyk** [comment]
```
5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
UBUNTU_CODENAME=jammy
```

**Comment by ruedigerp** [comment]
Hello, 

I have continued testing on a Debian host with k3s. 
We can exclude SELinux, Apparmor does not interfere either. So everything is ok. I have deactivated both services completely. 

On the host I see cgroups and cgroups2 

`
mount | grep cgroup
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,size=4096k,nr_inodes=1024,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
`

I don't see any in the container. So I looked once more in this direction and found several errors concerning cgroups2. 

Try the following: 

`
echo 'GRUB_CMDLINE_LINUX=systemd.unified_cgroup_hierarchy=false' > /etc/default/grub.d/cgroup.cfg
update-grub
reboot
`

After that start podloxx again and in the container logs there will be no more errors concerning cgroups. 
A `mount | grep cgroups` in the container will then also show the mounts.
